services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
  client:
    environment:
      - WDS_SOCKET_PORT=8080
    build: ./client
    ports:
      - 8080:3000
    volumes:
      - ./client/src:/app/src

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
